version: 1
jobs:
  build:
    working_directory: /dockercamp
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12
      - run:
          name: Install dependencies
          command: | 
            apk add --no-cache py-pip docker-compose
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockercamp python test.py
      - deploy:
          name: Push to dockerhub
          command: |
            docker login -u $dockerhub_user -p $dockerhub_token
            docker tag dockercamp_dockercamp $dockerhub_user/dockercamp:$CIRCLE_SHA1
            docker tag dockercamp_dockercamp $dockerhub_user/dockercamp:latest
            docker push $dockerhub_user/dockercamp:$CIRCLE_SHA1
            
