version: 1
jobs:
  build:
    working_directory: /dockercamp
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add -no-cache py-pip
            pip install docker-compose:1.15.0
        -run:
          name: Run tests
          command: |
            docker-compose up -d 
            docker-compose run dockercamp py test.py